changed runner

diff --git a/.github/workflows/ci_builds.yml b/.github/workflows/ci_builds.yml
--- a/.github/workflows/ci_builds.yml
+++ b/.github/workflows/ci_builds.yml
@@ -43,14 +43,16 @@ jobs:
 
     - name: Run `qmk mass-compile` (keymap ${{ matrix.keymap }})
       run: |
-        export NCPUS=$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || getconf _NPROCESSORS_ONLN 2>/dev/null)
-        qmk mass-compile -t -j $NCPUS -km ${{ matrix.keymap }} -e DUMP_CI_METADATA=yes || touch .failed
+        qmk compile -kb crkbd -km bob_layout -e CONVERT_TO=promicro_rp2040
+        qmk compile -kb crkbd -km default -e CONVERT_TO=promicro_rp2040
+        # export NCPUS=$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || getconf _NPROCESSORS_ONLN 2>/dev/null)
+        # qmk mass-compile -t -j $NCPUS -km ${{ matrix.keymap }} -e DUMP_CI_METADATA=yes || touch .failed
         # Generate the step summary markdown
-        ./util/ci/generate_failure_markdown.sh > $GITHUB_STEP_SUMMARY || true
+        # ./util/ci/generate_failure_markdown.sh > $GITHUB_STEP_SUMMARY || true
         # Truncate to a maximum of 1MB to deal with GitHub workflow limit
-        truncate --size='<960K' $GITHUB_STEP_SUMMARY || true
+        # truncate --size='<960K' $GITHUB_STEP_SUMMARY || true
         # Exit with failure if the compilation stage failed
-        [ ! -f .failed ] || exit 1
+        # [ ! -f .failed ] || exit 1
 
     - name: 'Upload artifacts'
       uses: actions/upload-artifact@v4
